exclude: ^(_build/|\.venv/)

default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v1.1.1
    hooks:
      - id: tombi-format
      - id: tombi-lint

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --exit-non-zero-on-fix
        language: system
        types_or:
          - python
          - jupyter

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or:
          - python
          - jupyter

      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types:
          - python
        exclude: \.ipynb$

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
        types:
          - python
        exclude: \.ipynb$

      - id: nbqa-pylint
        name: nbqa pylint
        entry: uv run nbqa pylint
        language: system
        types:
          - jupyter

      - id: nbqa-mypy
        name: nbqa mypy
        entry: uv run nbqa mypy
        language: system
        types:
          - jupyter

  # - repo: https://github.com/JuanJFarina/pymetrica
  #   rev: v1.5.6
  #   hooks:
  #     - id: pymetrica
